/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicAiVisionRouteImport } from './routes/api/public/ai-vision'
import { Route as ApiPublicAnalyzeChartRouteImport } from './routes/api/public/analyze-chart'
import { Route as ApiPublicCheckSubscriptionRouteImport } from './routes/api/public/check-subscription'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'
import { Route as ApiPublicPayfastRouteImport } from './routes/api/public/payfast'
import { Route as ApiPublicPayfastItnRouteImport } from './routes/api/public/payfast-itn'
import { Route as ApiPublicPaypalRouteImport } from './routes/api/public/paypal'
import { Route as ApiPublicPaypalWebhookRouteImport } from './routes/api/public/paypal-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiVisionRoute = ApiPublicAiVisionRouteImport.update({
  id: '/api/public/ai-vision',
  path: '/api/public/ai-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeChartRoute = ApiPublicAnalyzeChartRouteImport.update({
  id: '/api/public/analyze-chart',
  path: '/api/public/analyze-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckSubscriptionRoute =
  ApiPublicCheckSubscriptionRouteImport.update({
    id: '/api/public/check-subscription',
    path: '/api/public/check-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayfastRoute = ApiPublicPayfastRouteImport.update({
  id: '/api/public/payfast',
  path: '/api/public/payfast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayfastItnRoute = ApiPublicPayfastItnRouteImport.update({
  id: '/api/public/payfast-itn',
  path: '/api/public/payfast-itn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalRoute = ApiPublicPaypalRouteImport.update({
  id: '/api/public/paypal',
  path: '/api/public/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaypalWebhookRoute = ApiPublicPaypalWebhookRouteImport.update({
  id: '/api/public/paypal-webhook',
  path: '/api/public/paypal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ai-vision': typeof ApiPublicAiVisionRoute
  '/api/public/analyze-chart': typeof ApiPublicAnalyzeChartRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/payfast': typeof ApiPublicPayfastRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
  '/api/public/paypal': typeof ApiPublicPaypalRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ai-vision': typeof ApiPublicAiVisionRoute
  '/api/public/analyze-chart': typeof ApiPublicAnalyzeChartRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/payfast': typeof ApiPublicPayfastRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
  '/api/public/paypal': typeof ApiPublicPaypalRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/ai-vision': typeof ApiPublicAiVisionRoute
  '/api/public/analyze-chart': typeof ApiPublicAnalyzeChartRoute
  '/api/public/check-subscription': typeof ApiPublicCheckSubscriptionRoute
  '/api/public/news': typeof ApiPublicNewsRoute
  '/api/public/payfast': typeof ApiPublicPayfastRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
  '/api/public/paypal': typeof ApiPublicPaypalRoute
  '/api/public/paypal-webhook': typeof ApiPublicPaypalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/ai-vision'
    | '/api/public/analyze-chart'
    | '/api/public/check-subscription'
    | '/api/public/news'
    | '/api/public/payfast'
    | '/api/public/payfast-itn'
    | '/api/public/paypal'
    | '/api/public/paypal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/ai-vision'
    | '/api/public/analyze-chart'
    | '/api/public/check-subscription'
    | '/api/public/news'
    | '/api/public/payfast'
    | '/api/public/payfast-itn'
    | '/api/public/paypal'
    | '/api/public/paypal-webhook'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/ai-vision'
    | '/api/public/analyze-chart'
    | '/api/public/check-subscription'
    | '/api/public/news'
    | '/api/public/payfast'
    | '/api/public/payfast-itn'
    | '/api/public/paypal'
    | '/api/public/paypal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAiVisionRoute: typeof ApiPublicAiVisionRoute
  ApiPublicAnalyzeChartRoute: typeof ApiPublicAnalyzeChartRoute
  ApiPublicCheckSubscriptionRoute: typeof ApiPublicCheckSubscriptionRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
  ApiPublicPayfastRoute: typeof ApiPublicPayfastRoute
  ApiPublicPayfastItnRoute: typeof ApiPublicPayfastItnRoute
  ApiPublicPaypalRoute: typeof ApiPublicPaypalRoute
  ApiPublicPaypalWebhookRoute: typeof ApiPublicPaypalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-vision': {
      id: '/api/public/ai-vision'
      path: '/api/public/ai-vision'
      fullPath: '/api/public/ai-vision'
      preLoaderRoute: typeof ApiPublicAiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-chart': {
      id: '/api/public/analyze-chart'
      path: '/api/public/analyze-chart'
      fullPath: '/api/public/analyze-chart'
      preLoaderRoute: typeof ApiPublicAnalyzeChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-subscription': {
      id: '/api/public/check-subscription'
      path: '/api/public/check-subscription'
      fullPath: '/api/public/check-subscription'
      preLoaderRoute: typeof ApiPublicCheckSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payfast': {
      id: '/api/public/payfast'
      path: '/api/public/payfast'
      fullPath: '/api/public/payfast'
      preLoaderRoute: typeof ApiPublicPayfastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payfast-itn': {
      id: '/api/public/payfast-itn'
      path: '/api/public/payfast-itn'
      fullPath: '/api/public/payfast-itn'
      preLoaderRoute: typeof ApiPublicPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal': {
      id: '/api/public/paypal'
      path: '/api/public/paypal'
      fullPath: '/api/public/paypal'
      preLoaderRoute: typeof ApiPublicPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-webhook': {
      id: '/api/public/paypal-webhook'
      path: '/api/public/paypal-webhook'
      fullPath: '/api/public/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAiVisionRoute: ApiPublicAiVisionRoute,
  ApiPublicAnalyzeChartRoute: ApiPublicAnalyzeChartRoute,
  ApiPublicCheckSubscriptionRoute: ApiPublicCheckSubscriptionRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
  ApiPublicPayfastRoute: ApiPublicPayfastRoute,
  ApiPublicPayfastItnRoute: ApiPublicPayfastItnRoute,
  ApiPublicPaypalRoute: ApiPublicPaypalRoute,
  ApiPublicPaypalWebhookRoute: ApiPublicPaypalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
